
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-02
owner: ucsb-cs156-s26
repo_name: team01-s26-02
pull_requests: [{"author":{"id":"U_kgDOBztTrQ","is_bot":false,"login":"Makkerel","name":"Kevin "},"headRefName":"Kevin-DELETERecord","number":69,"title":"added DELETE for a UCSBorganization. 100% line/mutation coverage","url":"https://github.com/ucsb-cs156-s26/team01-s26-02/pull/69"},{"author":{"id":"U_kgDOCMR-Zg","is_bot":false,"login":"Andrew-UCSB","name":""},"headRefName":"Andrew-RecommendationRequestSingleDelete","number":68,"title":"Andrew recommendation request single delete","url":"https://github.com/ucsb-cs156-s26/team01-s26-02/pull/68"}]
